# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('ally', models.BooleanField(default=0)),
                ('villain', models.BooleanField(default=0)),
                ('bond_girl', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('owners', models.ManyToManyField(to='api_app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('allies', models.ManyToManyField(blank=True, related_name='allies', to='api_app.Character')),
                ('bond_girls', models.ManyToManyField(blank=True, related_name='bond_girls', to='api_app.Character')),
                ('gadgets', models.ManyToManyField(blank=True, to='api_app.Gadget')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('owner', models.ManyToManyField(to='api_app.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('weapon_type', models.CharField(max_length=15)),
                ('owners', models.ManyToManyField(to='api_app.Character')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='api_app.Vehicle'),
        ),
        migrations.AddField(
            model_name='movie',
            name='villains',
            field=models.ManyToManyField(blank=True, related_name='villains', to='api_app.Character'),
        ),
        migrations.AddField(
            model_name='movie',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='api_app.Weapon'),
        ),
        migrations.AddField(
            model_name='bondactor',
            name='movies',
            field=models.ManyToManyField(to='api_app.Movie'),
        ),
    ]
