# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadget',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='allies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='bond_girls',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='gadgets',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vehicles',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='villains',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='weapons',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='owners',
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(blank=True, to='api_app.Movie'),
        ),
        migrations.AddField(
            model_name='character',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.Vehicle'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='api_app.Weapon'),
        ),
    ]
