# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20160401_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='henchman',
            field=models.BooleanField(default=False),
        ),
    ]
