# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_character_henchman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weapons',
        ),
        migrations.AddField(
            model_name='character',
            name='gadgets_weapons',
            field=models.ManyToManyField(blank=True, to='api_app.Gadget'),
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
