# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20160401_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='gadgets_weapons',
        ),
        migrations.RemoveField(
            model_name='character',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='movie',
            name='gadgets_weapons',
            field=models.ManyToManyField(blank=True, to='api_app.Gadget'),
        ),
        migrations.AddField(
            model_name='movie',
            name='vehicle',
            field=models.ManyToManyField(blank=True, to='api_app.Vehicle'),
        ),
    ]
