# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20160402_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='vehicle',
            new_name='vehicles',
        ),
    ]
