# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 19:41
from __future__ import unicode_literals

from django.db import migrations
import csv

resources = [
    ('characters.csv', 'Character'),
    ('vehicles.csv', 'Vehicle'),
    ('gadgets.csv', 'Gadget'),
    ('movies.csv', 'Movie')
]


def create_data(apps, schema_editor):
    for resource in resources:
        with open(resource[0]) as infile:
            file_reader = csv.reader(infile)
            rows = [row for row in file_reader]
            headers = rows[0]
            data = rows[1:]

        Model = apps.get_model('api_app', resource[1])
        for row in data:
            Model.objects.create(**dict(zip(headers, row)))


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_auto_20160402_2127'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
