# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 19:41
from __future__ import unicode_literals

import csv
import psycopg2
from django.db import migrations
from james_bond_api.settings import DATABASES

conn = psycopg2.connect(
    dbname=DATABASES['default']['NAME'],
    user=DATABASES['default']['USER'],
    password=DATABASES['default']['PASSWORD'],
    host=DATABASES['default']['HOST'],
    port=DATABASES['default']['PORT']
)
cur = conn.cursor()
cur.execute("DELETE FROM ONLY api_app_character")


def create_data(apps, schema_editor):
    with open('characters.csv', newline='', encoding='utf-8') as infile:
        file_reader = csv.reader(infile)
        rows = [row for row in file_reader]
        headers = rows[0]
        data = rows[1:]

    Model = apps.get_model('api_app', 'Character')
    for row in data:
        row = list(map(lambda x: int(x) if x == '0' else x, row))
        Model.objects.create(**dict(zip(headers, row)))


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_auto_20160402_2127'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
